version: '3.8'
services:
  speech_to_text:
    container_name: speech_to_text
    build:
      context: speechtotext
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
  nlp:
    container_name: nlp
    build:
      context: nlp
      dockerfile: Dockerfile
    volumes:
      - ./Project_data:/Project_data
    ports:
      - "8989:8989"
  front:
    container_name: front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    depends_on:
      - speech_to_text
      - nlp
  graph:
    container_name: graph
    build:
      context: graph
      dockerfile: Dockerfile
    volumes:
      - ./Project_data:/Project_data
    ports:
      - "8000:8000"
