version: '3.8'
services:
  speech_to_text:
    container_name: speech_to_text
    build:
      context: speechtotext
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  nlp:
    container_name: nlp
    build:
      context: nlp
      dockerfile: Dockerfile
    ports:
      - "8989:8989"

