name: CI / CD T-AIA-910-REN_1

on:
  push:
    branches:
      - main
      - speech_to_text

jobs:
  tests:
    name: 'tests'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tests speech_to_text
        run: |
          cd speechtotext
          pip install -r requirements.txt
          python3 app.py &
          cd tests
          sleep 1
          curl localhost:5000
          python3 tests.py
